services:
  - type: web
    name: bjn-buscador
    runtime: python
    pythonVersion: "3.11.0"
    buildCommand: pip install -r requirements.txt && playwright install chromium --with-deps
    startCommand: python server.py
    envVars:
      - key: PORT
        value: 10000
    plan: free
